### ISSUE TITLE
Small visual fix

### ISSUE THREAD

**Issue by j-broo** [grae22/PeepStat#16]
Thinking the table shouldnt dynamically expand for the "wand" button. Should remain that size with some sort of placeholder. Bit jarring having it expand when the name is clicked on. Dont think the white space would look bad.

**Comment by grae22** [comment]
Updated (pushed to experimental site and master).

**Comment by grae22** [comment]
Eugh, not working properly on experimental site.

**Comment by grae22** [comment]
Nvm, just took a while to update.

**Comment by grae22** [comment]
Urg doesn't seem to work on mobile.

**Comment by grae22** [comment]
Jayzuz ok think it was a cache issue on my phone, seems to work.

**Comment by j-broo** [comment]
Looks good on PC, SIP browser and mobile.
