### ISSUE TITLE
Alphabetical sorting of people

### ISSUE THREAD

**Issue by j-broo** [grae22/PeepStat#17]
The "magic wand" button should disappear after a while?
Do i need to click elsewhere after clicking the person's name, to remove focus?
I'm testing on Opera, haven't seen behaviour on other browsers.

**Comment by j-broo** [comment]
Apologies, this does in fact work.
Weren't people sorted alphabetically in a previous build?

**Comment by grae22** [comment]
Yes. Yes they were. Sod... I'll check it out.

**Comment by grae22** [comment]
Pushed a fix to master & experimental.

**Comment by j-broo** [comment]
Fixed in master and experimental.
