### ISSUE TITLE
Dark theme; Centre entire page in browser

### ISSUE THREAD

**Issue by j-broo** [grae22/PeepStat#20]
Do you prefer a dark theme? Mobile friendly and easier on the eyes.

Also I think the whole page would look better if centred in browser.

**Comment by j-broo** [comment]
![untitled](https://cloud.githubusercontent.com/assets/26300538/24312672/40947886-10e2-11e7-8b25-02f3c32c80e6.png)

**Comment by grae22** [comment]
Could have an option to switch between light and dark? 

Yeah centred would be good.

**Comment by j-broo** [comment]
Pushed centering changes to master.

**Comment by j-broo** [comment]
Having the theme options would necessitate having separate light/dark dropdown icon buttons for contrast.
Current buttons not visible on dark theme. Should we go full on themes, or settle on a "look"?

Black is classic, hehe.

**Comment by j-broo** [comment]
Pushed black theme to experimental. Dropdown arrow icons updated.

**Comment by grae22** [comment]
Looks rad.

**Comment by j-broo** [comment]
You happy to close this? Centering in mobile doesn't work, only a problem in landscape mode.

**Comment by grae22** [comment]
Yeah can always revisit the centering issue.

**Comment by j-broo** [comment]
Good enough for V1.0. Closed.
