### ISSUE TITLE
Set CSS for hyperlinks so they're more visible?

### ISSUE THREAD

**Issue by grae22** [grae22/PeepStat#23]
Unvisited and visited links are a bit hard to see being dark blue & purple against black background.

**Comment by j-broo** [comment]
Yeah agreed. Maybe the same colour scheme as the "settings" link?

**Comment by grae22** [comment]
Have merged the dark theme into master and added CSS for hyperlinks.

**Comment by j-broo** [comment]
Definite improvement on dark theme, however, links and icons not very visible in contacts popup window. Perhaps needs to be revised to a dark transparent theme as well?

![untitled](https://cloud.githubusercontent.com/assets/26300538/24495443/6e83f648-1535-11e7-9aa9-28a12c15faaf.png)

**Comment by grae22** [comment]
Oh shit yeah forgot about that.

**Comment by grae22** [comment]
Moved dropdown styling to css - couldn't find a colour scheme I liked, maybe play with it?

**Comment by j-broo** [comment]
Hmm... my centering code seems to have broken. Did you merge the CSS file from the azure branch? I don;t think i ever pushed to master.

**Comment by j-broo** [comment]
Ah no, default.aspx needs to merge to master from azure.

**Comment by j-broo** [comment]
OK sorted it out. Messed up uploading files last time. Good news, centering in mobile works too.

CSS updated, let me know thoughts on dropdown and hover.

**Comment by grae22** [comment]
Lookin' good yo
