### ISSUE TITLE
Read-only view for people outside team

### ISSUE THREAD

**Issue by j-broo** [grae22/PeepStat#6]
For use by non-team members who need to keep track of team member statuses, but should not be able to update them.

**Comment by grae22** [comment]
There'd be a bunch of ways to do this, the simplest might be to have it read only by default, but when you click someone's name it allows you to then edit their statuses.

**Comment by grae22** [comment]
Ok... turns out that isn't easy at all.

**Comment by grae22** [comment]
Pushed experimental implementation as described above.

**Comment by j-broo** [comment]
Hidden link on member name is sufficient for these purposes. Works well.
