### ISSUE TITLE
Settings button/link

### ISSUE THREAD

**Issue by j-broo** [grae22/PeepStat#7]
Add settings icon in top right to take user to a management page, with the ability to add/edit/delete person entries. May add additional settings there. Should require a login. DB login would suffice.

Hopefully doesn't clutter main interface.

**Comment by j-broo** [comment]
Perhaps we should load names/extensions from CSV? Makes implementation and editing a lot simpler, and farms out the data curation to text file. We simply clear table and insert values from file each time.

Would need to clear statuses when importing so people don't end up with old/unrelated statues.

**Comment by j-broo** [comment]
Edit page header text on settings page, store in settings table.

**Comment by j-broo** [comment]
Setting idea: Select between extension URL prefix in settings page. Allow choice of 'sip:', 'tel:' (used by skype, etc) or 'mailto:'. Change 'Ext' column to 'Contact'.

**Comment by grae22** [comment]
Implemented basic settings page with login step (default password is 'admin').

**Comment by grae22** [comment]
Made some changes to settings table while doing this.

**Comment by j-broo** [comment]
I don't see the need for the delete option. Do we really want people to be able to delete an entire setting? Perhaps a 'clear' option, although I think 'edit' would suffice, if they want to clear it they can save an empty text box, as empty values are not really encouraged.

Key field should not be editable.

Deleting the entire row has potential to break the software, which it did when I deleted the SettingsPassword key.

**Comment by grae22** [comment]
So the settings will all be predefined, just the values editable?

**Comment by j-broo** [comment]
I think so. When would they need to be editable? That's why i never included the key column initially, expected to rely on the Id column to identify the setting.

I suppose the DB would have a bunch of defaults that you can edit.

**Comment by grae22** [comment]
Ditched the delete option.

**Comment by grae22** [comment]
Oh should prob ditch the new button, too.

**Comment by grae22** [comment]
Ditched it.

**Comment by j-broo** [comment]
I think the cog button should go, and we go for a 'settings' link bottom right under the table? same line as the version number etc?

**Comment by grae22** [comment]
Cool.

**Comment by grae22** [comment]
Done.

**Comment by j-broo** [comment]
Settings link is fine. No need for further work here.
