### ISSUE TITLE
Multiple contact options: SIP/Tel/Email

### ISSUE THREAD

**Issue by j-broo** [grae22/PeepStat#8]
Ability to select a contact protocol from settings page. Global setting. Choose from either SIP, Tel or Email.

Setting stored in settings table. Suggest doing this by loading URL prefix string from table and creating link dynamically, so either 'sip:', 'tel:', or 'mailto:'

Setting doesn't need to be per-person.

**Comment by grae22** [comment]
Just a thought... in read-only mode, clicking on a status (probably only 'yes' statuses) could do this. So, any 'yes' statuses are also hyperlinks with relevant sip/tel/mailto address.

**Comment by j-broo** [comment]
I'm not sold on reusing the buttons for this, i think it has the potential to be confusing. I think it would be better to leave those to the sole purpose of enabling/disabling status.

Perhaps we can update main page to replace tel no with a contact button. When clicked it allows selection of sip/tel/email?

The initial idea behind having the contact number visible was to cater for people who may not be using a softphone, as it gives a visual reference for the number. May still be feasible if clicking on the 'contact' button displays the extention/tel no/email address?

**Comment by grae22** [comment]
Yeah +1 on confusion.

**Comment by grae22** [comment]
Tooling around with dropdown, see http://teamtrackerexperimental.azurewebsites.net/Default.aspx for demo. Looks crappy, but concept?

**Comment by grae22** [comment]
Updated the experimental ver, drop simply displays 'email' & 'skype'.

**Comment by grae22** [comment]
Still need to add setting for default contact type which will influence what is displayed in contact column and what shows in the dropdown.

**Comment by grae22** [comment]
Added setting (prev comment) to experimental ver.

**Comment by j-broo** [comment]
Drop-down looks super rad. Liking the transparency and lack of clutter. Can't click out of it though. OK... i see you can by clicking the arrow again...

**Comment by grae22** [comment]
I'll bring it into the master branch when I get a mo, entails some db changes.

**Comment by grae22** [comment]
Have integrated dropdown into master.

**Comment by grae22** [comment]
Anything else we need on this?

**Comment by j-broo** [comment]
Dropdown doesn;t display properly on some browsers.
![dropdown](https://cloud.githubusercontent.com/assets/26300538/24202310/5beb2b7a-0f1b-11e7-8cf4-4045c1c04377.png)

My BB10 browser and the bulit-in browser on our SIP client. not sure what that is based on.

**Comment by grae22** [comment]
Pushed potential fix to experimental site.

**Comment by grae22** [comment]
Fix merged into master.

**Comment by j-broo** [comment]
Just a thought, perhaps skype link should start a chat?

See here: http://stackoverflow.com/questions/2841676/how-to-start-skype-chat-not-call-with-link

My intention was that at least.

For the tel: prefix we should alternate that with sip: or have a separate call option for example for cell/landline no. I know i can set my sip client to dial tel: links instead of skype doing it.

**Comment by grae22** [comment]
Ja I like that for skype chat.

So cols for cell/landline, skype-call & skype-cat?

**Comment by j-broo** [comment]
I reckon lets offer sip/tel:, mailto and skype chat?

**Comment by grae22** [comment]
You want to be able to choose between sip & tel within the same 'column' (on the main page)?

**Comment by j-broo** [comment]
I'll have to test. I think sip: dials any number if you have a sip client installed. Tel: is specifically a skype or similar thing. I'll confirm...

**Comment by j-broo** [comment]
OK sip and tel seem to be kind of interchangeable. On PC, tel launches whatever the default app for the link is. In my case, skype. On mobile, it initiates a call. So I think let's leave it to the user to choose in the import file, no need to have separate contact options.

**Comment by grae22** [comment]
Cool, so nothing more to do here?

**Comment by j-broo** [comment]
No, i think this is done. We can deal qith any glitches etc later if they crop up.
