### ISSUE TITLE
DB population from CSV

### ISSUE THREAD

**Issue by j-broo** [grae22/PeepStat#9]
Perhaps we should load names/contact info from CSV? Makes implementation and editing a lot simpler, and farms out the data curation to text file. We simply clear table and insert values from file each time.

Would need to clear statuses when importing so people don't end up with old/unrelated statuses.

**Comment by grae22** [comment]
Would you want to do this continuously (i.e. on a regular schedule) or as an option (probably via the settings page)?

**Comment by j-broo** [comment]
Definitely a once-off thing, on demand, via the settings page. I see no reason to do this regularly unless some other system is pushing info regularly to the CSV, which I don't see happening at this stage, if at all.

**Comment by grae22** [comment]
Import should work - see ImportExample.txt in root folder.

**Comment by grae22** [comment]
Export implemented.

**Comment by j-broo** [comment]
Import tested, works fine. I think this will suffice for now unless app scope changes in future.
